(WIP) osVoice decomp tracking
decompals/ultralib pull request #15
Opened 2022-03-03 13:45 UTC by someone2639

Important things to review:
-the Decompollaborate/mm repo has some of these decompiled in some form, which I adapted to this branch; however, defines such as `CONT_ERR_CONTRFAIL` are not in this repo by default, while they do show up in the `mm` repo

**Very** important things to review
-I wrote an essay in src/voice/voicecountsyllables.c and I have no idea if it's correct or useful

Will update description as I go

2022-03-03 19:53 UTC, Mr-Wiseguy requested changes

2022-03-03 19:53 UTC, Mr-Wiseguy commented on include/controller.h
> +#ifndef _CONTROLLER_H_
We have a controller.h in the repo already in src/io, is this one needed? This one seems to have some game-specific variables/structs and custom button defines that are equivalent to the standard ones.

2022-03-03 19:53 UTC, Mr-Wiseguy commented on include/PR/os_voice.h
> +#ifndef _OS_VOICE_H_
Go ahead and re-add the notice at the top of this file, we'll be reverting that change to all other files shortly

2022-03-03 19:53 UTC, Mr-Wiseguy commented on include/PR/os.h
> -
If you rebase on current main, these line endings will have already been fixed

2022-03-05 18:15 UTC, EllipticEllipsis reviewed
It's tricky to walk the line between respecting the SDK names and accurately documenting what this is actually doing. I've made a few linguistically-inclined comments, but I'm not sure how many are actually going to be possible to act on.

2022-03-05 18:15 UTC, EllipticEllipsis commented on src/voice/voicecountsyllables.c
> +}
```suggestion
}

```

2022-03-05 18:15 UTC, EllipticEllipsis commented on src/voice/voiceinit.c
> +    static u8 cmd[] = {0x1E, 0x6E, 0x08, 0x56, 0x03};
Presumably there will be macros associated to these in future?

2022-03-05 18:15 UTC, EllipticEllipsis commented on src/voice/voicecontrolgain.c
> +#define ACOUNT(a) (sizeof((a)) / sizeof((a[0])))
I have to admit I'm somewhat baffled by the presence of this macro here, when it doesn't seem to be used at all in this file.

2022-03-10 01:48 UTC, Mr-Wiseguy requested changes

2022-03-10 01:48 UTC, Mr-Wiseguy commented on src/io/controller.h
> +/* Controller error number */
These defines are already present in os_cont.h

2022-03-10 01:48 UTC, Mr-Wiseguy commented on src/io/controller.h
> +} __OSContRequestHeaderAligned; // size = 0x6
This struct should be named "__OSContRequesFormatShort" and the "poll" member should be named "cmd"

2022-03-10 01:48 UTC, Mr-Wiseguy commented on src/voice/voicecontread36.c
> +            ptr[0] = 0xFF;
These correspond to struct offsets to structs in controller_voice.h, which you can find with libelf.py. Take a look at this scratch to see how they'd get used: https://decomp.me/scratch/PTDM7

2022-03-15 19:25 UTC, someone2639 commented
just kidding _now_ everything is ready

2022-03-15 19:46 UTC, Mr-Wiseguy requested changes
Mostly formatting or symbolization changes.

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicesetword.c
> +    bzero(buf, 40);
Same deal here with the constants used for buf as in voicemaskdictionary.c

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicesetword.c
> +    // if (k >= 0x22) {
Commented code can be removed.

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicesetword.c
> +            ret = 0xD;
These return values are one of CONT_ERR_x in os_cont.h

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicegetstatus.c
> +            *ptr++ = 1;
These two lines are another pair of TX and RX sizes.

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicegetreaddata.c
> +}
No newline at end of file

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicecontread36.c
> +            if (__osVoiceContDataCrc(&READ36FORMAT(ptr)->data, 36) != READ36FORMAT(ptr)->datacrc) {
The 36 here can be an `ARRLEN(READ36FORMAT(ptr)->data)`

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicecontread36.c
> +        ret = (READ36FORMAT(ptr)->rxsize & 0xC0) >> 4;
This is the `CHNL_ERR` macro from controller.h

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicecontread36.c
> +                bcopy(&READ36FORMAT(ptr)->data, buffer, 36);
Same as the ARRLEN comment above.

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicecontrolgain.c
> +#define ACOUNT(a) (sizeof((a)) / sizeof((a[0])))
This macro is unused and can be removed.

2022-03-15 19:46 UTC, Mr-Wiseguy commented on src/voice/voicegetstatus.c
> +        ret = (u8)((header.rxsize & 0xC0) >> 4);
This is the `CHNL_ERR` macro in controller.h

2022-03-15 20:20 UTC, someone2639 commented
Comments addressed

2022-03-15 20:39 UTC, Mr-Wiseguy approved these changes
Lgtm

2022-03-15 20:44 UTC, merged