rmon files, initialize files, kdebugserver.c, initrdb.c for libgultra_d
decompals/ultralib pull request #25
Opened 2022-03-24 01:09 UTC by Thar0

2022-03-24 14:36 UTC, Mr-Wiseguy requested changes
Basically good to go, just a small question and change.

2022-03-24 15:50 UTC, Thar0 commented on src/os/initialize_emu.c
> +#ifndef _FINALROM
They are built regardless of whether they are included in the final archive, and several files require defines that are wrapped in `FINALROM` in headers, so I have to wrap the c code that uses those defines else it will cause build errors.

2022-03-26 02:05 UTC, Thar0 commented on src/rmon/rmonprint.c
> +#ifndef _FINALROM
Done

2022-03-26 02:07 UTC, Mr-Wiseguy approved these changes

2022-03-26 02:07 UTC, merged