Match libgultra_d.a and libgultra.a
decompals/ultralib pull request #36
Opened 2023-02-13 05:14 UTC by Mr-Wiseguy

The big one

2023-02-14 02:09 UTC, hensldm reviewed
A few things I noticed, mainly with stuff I did

2023-02-14 14:36 UTC, Thar0 requested changes
Left out lots of formatting related things since the whole repo is in a dire situation in that respect, but had to include a few. Otherwise, looks mostly good

2023-02-14 14:36 UTC, Thar0 commented on src/error/errorasm.s
> +#endif
No newlines at the end of lots of files 😭 
(eventually I want to look into a formatter so this could wait I guess)

2023-02-14 14:36 UTC, Thar0 commented on include/asm.h
> +#include <sys/asm.h>
What's this for?

2023-02-14 14:36 UTC, Thar0 commented on src/debug/profile.c
> +                bytesThisBlock = (totalBytes < 0x800U) ? totalBytes : 0x800;
Is the `U` qualifier needed?

2023-02-14 14:36 UTC, Thar0 commented on src/debug/profile.c
> +            *(t->histo_base + i) = 0;
I guess `t->histo_base[i] = 0` doesn't match?

2023-02-14 14:36 UTC, Thar0 commented on src/debug/profile.c
> +    osSetTimer(&__osProfTimer, 0, OS_USEC_TO_CYCLES(microseconds), &__osProfTimerQ, 0);
```suggestion
    osSetTimer(&__osProfTimer, 0, OS_USEC_TO_CYCLES(microseconds), &__osProfTimerQ, NULL);
```
Last arg is `OSMesg`

2023-02-14 14:36 UTC, Thar0 commented on src/error/commonerror.c
> +}
```suggestion
    osSyncPrintf("\n");

    va_end(argPtr);
}
```

2023-02-14 14:36 UTC, Thar0 commented on src/flash/flashgetaddr.c
> +    devAddr = page_num * 128;
```suggestion
        devAddr = page_num * 64;
    } else {
        devAddr = page_num * 128;
```

2023-02-14 14:36 UTC, Thar0 commented on src/io/contpfs.c
> +    return sum & 0xFFFF;
```suggestion
    return (u16)sum;
```
?

2023-02-14 14:36 UTC, Thar0 commented on src/io/dpsetnextbuf.c
> +    while (1) {
```suggestion
    while (TRUE) {
```

2023-02-14 14:36 UTC, Thar0 commented on src/io/epilinkhandle.c
> +    saveMask = __osDisableInt();
Is this really needed to match? I would be very surprised if so

2023-02-14 14:36 UTC, Thar0 commented on src/io/pfsallocatefile.c
> +        ext_name, file_no)) != 0) && ret != PFS_ERR_INVALID) {
```suggestion
    if (((ret = osPfsFindFile(pfs, company_code, game_code, game_name, ext_name, file_no)) != 0)
        && ret != PFS_ERR_INVALID) {
```

2023-02-14 14:36 UTC, Thar0 commented on src/io/pfsallocatefile.c
> +        NULL, NULL, file_no)) != 0) && ret != PFS_ERR_INVALID) {
```suggestion
    if (((ret = osPfsFindFile(pfs, 0, 0, NULL, NULL, file_no)) != 0)
        && ret != PFS_ERR_INVALID) {
```

2023-02-14 14:36 UTC, Thar0 commented on src/io/cartrominit.c
> +	}
```suggestion
	WAIT_ON_IOBUSY(stat);
```

2023-02-14 14:36 UTC, Thar0 commented on src/io/vigetnextframebuf.c
> +    return(framep);
🤔

2023-02-14 14:36 UTC, Thar0 commented on src/io/visetspecial.c
> +    | OS_VI_DIVOT_OFF | OS_VI_DITHER_FILTER_ON | OS_VI_DITHER_FILTER_OFF))) {
Define for the upper bound may make this more readable?

2023-02-14 14:36 UTC, Thar0 commented on src/log/delay.s
> +.set reorder
```suggestion
1:
    subu    t0,1
    NOP
    NOP
    bnez    t0,1b
```

2023-02-14 14:36 UTC, Thar0 commented on src/log/log.c
> +    __osLogWrite(log, code, numArgs, argPtr);
```suggestion
    va_start(argPtr, numArgs);
    __osLogWrite(log, code, numArgs, argPtr);
    va_end(argPtr);
```

2023-02-14 15:05 UTC, Mr-Wiseguy commented on include/asm.h
> +#include <sys/asm.h>
monutil's mdebug requires this include redirection to match. It has to include `asm.h` and that has to include `sys/asm.h`.

2023-02-14 15:08 UTC, Mr-Wiseguy commented on src/debug/profile.c
> +                bytesThisBlock = (totalBytes < 0x800U) ? totalBytes : 0x800;
It is, otherwise the codegen is incorrect (`slti` vs `sltiu`). The irix _d build's mdebug also reveals that `totalBytes` is an s32 so it can't be resolved by making that unsigned instead. The second 0x800 can have the U suffix and still match, which at least makes them consistent so I'll make that change.

2023-02-14 15:09 UTC, Mr-Wiseguy commented on src/debug/profile.c
> +            *(t->histo_base + i) = 0;
It does, so I'll change it.

2023-02-14 15:11 UTC, Mr-Wiseguy commented on src/io/contpfs.c
> +    return sum & 0xFFFF;
Neither the cast nor mask are required because the function already returns a `u16`, so I'll remove it.

2023-02-14 15:12 UTC, Mr-Wiseguy commented on src/io/epilinkhandle.c
> +    saveMask = __osDisableInt();
Yeah, they can be combined into one statement and still match.

2023-02-14 15:17 UTC, Mr-Wiseguy commented on src/log/delay.s
> +.set reorder
This does still match so I'll make this change.

2023-03-06 21:54 UTC, hensldm reviewed
Also agree that it would be nice to setup up a formatter.

2023-03-06 21:54 UTC, hensldm commented on src/libc/xprintf.c
> +            }
This looks like it is still `ATOI`.

2023-03-06 21:59 UTC, hensldm commented on src/io/vimgr.c
>              osSetThreadPri(0, oldPri);
```suggestion
            osSetThreadPri(NULL, oldPri);
```

2023-03-18 02:16 UTC, hensldm commented on tools/Makefile
> +	wget https://github.com/decompals/ido-static-recomp/releases/download/v0.5/ido-5.3-recomp-ubuntu-20.04.tar.gz
```suggestion
	wget https://github.com/decompals/ido-static-recomp/releases/download/v0.6/ido-5.3-recomp-ubuntu-20.04.tar.gz
```
Going to want to update this to v0.6. v0.5 has a bug that left empty temp files dangling in `/tmp`.

2023-03-18 11:11 UTC, AngheloAlf commented on tools/Makefile
> +	wget https://github.com/decompals/ido-static-recomp/releases/download/v0.5/ido-5.3-recomp-ubuntu-20.04.tar.gz
If you like to live on the bleeding edge:
```suggestion
	wget https://github.com/decompals/ido-static-recomp/releases/latest/download/ido-5.3-recomp-ubuntu-20.04.tar.gz
```

2023-03-18 11:15 UTC, AngheloAlf commented on src/voice/voicestopreaddata.c
> +    }
wouldn't this break `_rom.a` builds?

2023-03-18 11:25 UTC, AngheloAlf commented on src/rg/region.c
>  void *osCreateRegion(void *startAddress, u32 length, u32 bufferSize, u32 alignSize) {
10/10

2023-03-18 11:27 UTC, AngheloAlf commented on src/rg/free.c
> +    assert((region != NULL) && (addr != NULL));
I noticed there are some `asserts` inside `_DEBUG` blocks and other outside. Can this be made consistent or it would break matching?

2023-03-18 18:24 UTC, hensldm commented on src/debug/assert.c
> +	__assertBreak;
Pretty sure it calls the asm function in `assertbreak.s`

2023-03-18 19:00 UTC, AngheloAlf commented on src/debug/assert.c
> +	__assertBreak;
But this is C, and to call a function you need to do  `__assertBreak()`.
So either this expands to a macro I missed or I have no clue what's going on

2023-03-18 20:25 UTC, hensldm commented on src/debug/assert.c
> +	__assertBreak;
Oh I missed the lack of `()`. I'm not sure then. It actually seems to match fine when I remove it

2023-04-01 03:12 UTC, hensldm commented on src/error/errorasm.s
> +#endif
I think I got them all. Let me know if I missed one.

2023-04-01 03:12 UTC, hensldm commented on src/io/pfsallocatefile.c
> +        ext_name, file_no)) != 0) && ret != PFS_ERR_INVALID) {
With everything on one line it actually isn't even as long as the function header, so just put the whole if on one line. Let me know if it should still be split.

2023-04-01 03:21 UTC, hensldm commented on src/io/cartrominit.c
> +	}
Also did the same for `__osGIORawInterrupt`

2023-04-01 03:24 UTC, hensldm commented on src/io/visetspecial.c
> +    | OS_VI_DIVOT_OFF | OS_VI_DITHER_FILTER_ON | OS_VI_DITHER_FILTER_OFF))) {
Went with `OS_VI_SPECIAL_MAX` for the define name and just put it directly in the c file. Does that seem fine?

2023-04-01 03:28 UTC, hensldm commented on src/voice/voicestopreaddata.c
> +    }
It kind of surprises me too, but `_rom.a` still builds fine.

2023-04-01 03:31 UTC, hensldm commented on src/rg/free.c
> +    assert((region != NULL) && (addr != NULL));
Tried on the one in `osCreateRegion`, but seems to break matching for `libgultra_d` builds.

2023-04-01 16:55 UTC, hensldm reviewed
I'm willing to fix these up as well, but just wanted to get some peoples thoughts first.

2023-04-01 16:55 UTC, hensldm commented on src/io/controller.c
>              data->status = requestHeader.status;
```suggestion
        if (data->errno != 0) {
            continue;
        }
        
        data->type = requestHeader.typel << 8 | requestHeader.typeh;
        data->status = requestHeader.status;
```
This also matches and seems better?

2023-04-01 16:55 UTC, hensldm commented on src/io/pfsgetstatus.c
> +    if (data->errno) {
```suggestion
    if (data->errno != 0) {
```
There is also another instance of this in `__osPfsGetInitData`.

2023-04-01 16:55 UTC, hensldm commented on src/io/epirawread.c
> +#include <assert.h>
Should this also be ""? Note this applies to many different files with difference includes. For example `<rdb.h>` in `pimgr.c`.

2023-04-01 22:34 UTC, hensldm approved these changes
:)

2023-04-03 02:12 UTC, merged